"use client";

import {
  AlignLeft,
  Binary,
  Bot,
  Braces,
  Calculator,
  Clock,
  Code2,
  Database,
  Diff,
  Eraser,
  FileCode,
  FileDown,
  FileSpreadsheet,
  FileStack,
  FileText,
  Fingerprint,
  Gauge,
  Globe,
  Hash,
  Image as ImageIcon,
  Inbox,
  KeyRound,
  Link2,
  Lock,
  Mail,
  Map,
  MapPin,
  Mic,
  Minimize2,
  Minus,
  Palette,
  Pipette,
  QrCode,
  Radio,
  RefreshCw,
  Regex,
  Ruler,
  ScanText,
  Scissors,
  Search,
  Send,
  ShieldCheck,
  Tags,
  Type,
  UserRound,
  Wand2,
  Youtube,
  type LucideIcon,
} from "lucide-react";
import type { ToolIconName } from "@/lib/tool-icon-name";
import { cn } from "@/lib/utils";

const iconMap: Record<ToolIconName, LucideIcon> = {
  mail: Mail,
  inbox: Inbox,
  "qr-code": QrCode,
  "minimize-2": Minimize2,
  "file-text": FileText,
  "file-stack": FileStack,
  scissors: Scissors,
  bot: Bot,
  database: Database,
  lock: Lock,
  palette: Palette,
  "file-code": FileCode,
  "user-round": UserRound,
  youtube: Youtube,
  "scan-text": ScanText,
  mic: Mic,
  "refresh-cw": RefreshCw,
  "wand-2": Wand2,
  search: Search,
  "map-pin": MapPin,
  gauge: Gauge,
  tags: Tags,
  map: Map,
  braces: Braces,
  minus: Minus,
  "code-2": Code2,
  "file-down": FileDown,
  regex: Regex,
  "file-spreadsheet": FileSpreadsheet,
  binary: Binary,
  "key-round": KeyRound,
  "link-2": Link2,
  hash: Hash,
  send: Send,
  "shield-check": ShieldCheck,
  radio: Radio,
  pipette: Pipette,
  type: Type,
  "align-left": AlignLeft,
  diff: Diff,
  calculator: Calculator,
  eraser: Eraser,
  clock: Clock,
  fingerprint: Fingerprint,
  image: ImageIcon,
  ruler: Ruler,
  globe: Globe,
};

interface ToolIconProps {
  name: ToolIconName;
  className?: string;
}

export function ToolIcon({ name, className }: ToolIconProps) {
  const Icon = iconMap[name];
  return <Icon className={cn("h-5 w-5", className)} />;
}
