import { Module } from '@nestjs/common';
import {
  ApiTesterController,
  Base64Controller,
  CaseConverterController,
  CodeReaderController,
  ContrastCheckerController,
  ColorPickerController,
  CronParserController,
  CssMinifierController,
  CsvJsonController,
  HashGeneratorController,
  HtmlEntitiesController,
  HtmlStripperController,
  HtmlToMarkdownController,
  JsBeautifierController,
  JsonFormatterController,
  JsonValidatorController,
  JwtDecoderController,
  LoremIpsumController,
  MetaTagsController,
  OtpDetectorController,
  RegexTesterController,
  RobotsTxtController,
  SitemapController,
  TextDiffController,
  TimestampConverterController,
  UnitConverterController,
  UrlEncoderController,
  UserAgentParserController,
  UuidGeneratorController,
  WordCounterController,
} from './devtools.controllers';
import { DevtoolsCoreService } from './services/devtools-core.service';

@Module({
  controllers: [
    MetaTagsController,
    RobotsTxtController,
    SitemapController,
    JsonValidatorController,
    JsonFormatterController,
    CssMinifierController,
    JsBeautifierController,
    HtmlToMarkdownController,
    RegexTesterController,
    CsvJsonController,
    Base64Controller,
    JwtDecoderController,
    UrlEncoderController,
    UuidGeneratorController,
    ApiTesterController,
    OtpDetectorController,
    CodeReaderController,
    ColorPickerController,
    ContrastCheckerController,
    LoremIpsumController,
    CaseConverterController,
    TextDiffController,
    WordCounterController,
    HtmlStripperController,
    TimestampConverterController,
    CronParserController,
    HashGeneratorController,
    UnitConverterController,
    UserAgentParserController,
    HtmlEntitiesController,
  ],
  providers: [DevtoolsCoreService],
})
export class DevtoolsModule {}
