import 'package:flutter/material.dart';

IconData iconForToolName(String name) {
  switch (name) {
    case 'mail':
    case 'inbox':
      return Icons.mail_outline;
    case 'qr-code':
      return Icons.qr_code_2;
    case 'minimize-2':
      return Icons.compress;
    case 'file-text':
      return Icons.description_outlined;
    case 'file-stack':
      return Icons.layers_outlined;
    case 'scissors':
      return Icons.content_cut;
    case 'bot':
      return Icons.smart_toy_outlined;
    case 'database':
      return Icons.storage_outlined;
    case 'lock':
    case 'key-round':
      return Icons.lock_outline;
    case 'palette':
    case 'pipette':
      return Icons.palette_outlined;
    case 'file-code':
      return Icons.code_off;
    case 'user-round':
      return Icons.person_outline;
    case 'youtube':
      return Icons.play_circle_outline;
    case 'scan-text':
      return Icons.document_scanner_outlined;
    case 'mic':
      return Icons.mic_outlined;
    case 'refresh-cw':
      return Icons.refresh;
    case 'wand-2':
      return Icons.auto_fix_high;
    case 'search':
      return Icons.search;
    case 'map-pin':
      return Icons.location_on_outlined;
    case 'gauge':
      return Icons.speed;
    case 'tags':
      return Icons.sell_outlined;
    case 'map':
      return Icons.map_outlined;
    case 'braces':
      return Icons.data_object;
    case 'minus':
      return Icons.remove;
    case 'code-2':
      return Icons.javascript;
    case 'file-down':
      return Icons.download_outlined;
    case 'regex':
      return Icons.find_replace_outlined;
    case 'file-spreadsheet':
      return Icons.table_chart_outlined;
    case 'binary':
      return Icons.pin_outlined;
    case 'link-2':
      return Icons.link;
    case 'hash':
      return Icons.tag;
    case 'send':
      return Icons.send_outlined;
    case 'shield-check':
      return Icons.verified_user_outlined;
    case 'radio':
      return Icons.podcasts;
    case 'type':
      return Icons.text_fields;
    case 'align-left':
      return Icons.format_align_left;
    case 'diff':
      return Icons.difference_outlined;
    case 'calculator':
      return Icons.calculate_outlined;
    case 'eraser':
      return Icons.auto_delete_outlined;
    case 'clock':
      return Icons.schedule;
    case 'fingerprint':
      return Icons.fingerprint;
    case 'image':
      return Icons.image_outlined;
    case 'ruler':
      return Icons.straighten;
    case 'globe':
      return Icons.public;
    default:
      return Icons.build_circle_outlined;
  }
}
