import type { ToolIconName } from "./tool-icon-name";

export type ToolCategory =
  | "Encoding"
  | "Formatting"
  | "Generators"
  | "Network"
  | "Identity"
  | "Email"
  | "Text"
  | "Color"
  | "Time"
  | "Security"
  | "Web"
  | "Media"
  | "AI"
  | "PDF"
  | "SEO";

export interface Tool {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: ToolCategory;
  icon: ToolIconName;
  accent: "violet" | "cyan" | "fuchsia" | "amber" | "emerald";
  status: "ready" | "soon";
  keywords: string[];
  featured?: boolean;
}

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function toolHref(tool: Tool): string {
  if (tool.status === "ready") {
    return `/tools/${tool.slug}`;
  }
  return "/tools";
}

export const categories: ToolCategory[] = [
  "Formatting",
  "Encoding",
  "Generators",
  "AI",
  "PDF",
  "Email",
  "Text",
  "Media",
  "Security",
  "Color",
  "Web",
  "SEO",
  "Network",
  "Identity",
  "Time",
];

export const tools: Tool[] = [
  {
    slug: "temp-mail",
    name: "Temp Mail",
    tagline: "Temporary email & fake inbox",
    description:
      "Disposable email for OTP, signups and testing. Millions use it daily for verifications without spam.",
    category: "Email",
    icon: "mail",
    accent: "emerald",
    status: "ready",
    featured: true,
    keywords: [
      "temp mail",
      "temporary email",
      "fake email generator",
      "disposable",
      "otp",
      "signup",
    ],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    tagline: "Custom colors, logo & analytics",
    description:
      "Create QR codes with custom colors, logo upload, dynamic URLs and scan analytics.",
    category: "Generators",
    icon: "qr-code",
    accent: "amber",
    status: "ready",
    featured: true,
    keywords: ["qr code generator", "create qr code", "barcode", "dynamic qr"],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    tagline: "Reduce image size instantly",
    description:
      "Compress PNG, JPG and WebP with smart optimization. Perfect for bloggers, developers and students.",
    category: "Media",
    icon: "minimize-2",
    accent: "violet",
    status: "ready",
    featured: true,
    keywords: ["compress image", "reduce image size", "optimize", "webp"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    tagline: "Convert PDF to editable DOCX",
    description: "Transform PDF documents into editable Word files with layout preservation.",
    category: "PDF",
    icon: "file-text",
    accent: "cyan",
    status: "ready",
    featured: true,
    keywords: ["pdf to word", "convert pdf", "docx"],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    tagline: "Combine multiple PDFs",
    description: "Drag, drop and merge PDF files into one document in seconds.",
    category: "PDF",
    icon: "file-stack",
    accent: "fuchsia",
    status: "ready",
    keywords: ["merge pdf", "combine pdf", "join pdf"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    tagline: "Extract pages from PDF",
    description: "Split PDFs by page range or extract individual pages as separate files.",
    category: "PDF",
    icon: "scissors",
    accent: "amber",
    status: "ready",
    keywords: ["split pdf", "extract pages", "pdf pages"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    tagline: "Shrink PDF file size",
    description: "Reduce PDF size for email and uploads without losing readability.",
    category: "PDF",
    icon: "minimize-2",
    accent: "emerald",
    status: "ready",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
  },
  {
    slug: "ai-code-generator",
    name: "AI Code Generator",
    tagline: "Generate code with AI",
    description:
      "Describe what you need and get production-ready snippets in any language. Huge SaaS potential.",
    category: "AI",
    icon: "bot",
    accent: "violet",
    status: "ready",
    featured: true,
    keywords: ["ai code generator", "generate code with ai", "copilot"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    tagline: "Beautify & build queries",
    description:
      "Format and beautify SQL with syntax highlighting plus a visual query builder for developers.",
    category: "Formatting",
    icon: "database",
    accent: "cyan",
    status: "ready",
    featured: true,
    keywords: ["sql formatter", "sql beautifier", "query builder"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    tagline: "Strong passwords + breach check",
    description:
      "Generate secure passwords with strength scoring and Have I Been Pwned breach detection.",
    category: "Security",
    icon: "lock",
    accent: "emerald",
    status: "ready",
    featured: true,
    keywords: [
      "strong password generator",
      "secure password",
      "breach checker",
      "password strength",
    ],
  },
  {
    slug: "palette-generator",
    name: "Color Palette Generator",
    tagline: "Palettes & gradient builder",
    description:
      "Generate harmonious palettes, CSS gradients and export tokens for designers and developers.",
    category: "Color",
    icon: "palette",
    accent: "violet",
    status: "ready",
    featured: true,
    keywords: ["color palette generator", "gradient generator", "scheme", "design"],
  },
  {
    slug: "markdown-editor",
    name: "Markdown Editor",
    tagline: "Write & preview live",
    description:
      "Split-pane Markdown editor with live HTML preview. Built for GitHub developers and docs.",
    category: "Text",
    icon: "file-code",
    accent: "fuchsia",
    status: "ready",
    featured: true,
    keywords: ["markdown editor online", "markdown preview", "md editor"],
  },
  {
    slug: "ai-resume-builder",
    name: "AI Resume Builder",
    tagline: "AI CV generator",
    description:
      "Build ATS-friendly resumes and CVs with AI suggestions. High-traffic, professional templates.",
    category: "AI",
    icon: "user-round",
    accent: "amber",
    status: "ready",
    featured: true,
    keywords: ["resume builder", "ai cv generator", "curriculum vitae"],
  },
  {
    slug: "youtube-thumbnail",
    name: "YouTube Thumbnail Downloader",
    tagline: "HD thumbnails in one click",
    description: "Download max-resolution YouTube thumbnails by URL. Viral search volume tool.",
    category: "Media",
    icon: "youtube",
    accent: "fuchsia",
    status: "ready",
    keywords: ["youtube thumbnail downloader", "yt thumbnail", "video thumb"],
  },
  {
    slug: "image-to-text",
    name: "Screenshot to Text",
    tagline: "OCR online — image to text",
    description:
      "Extract text from screenshots and images with OCR. For students, offices and AI workflows.",
    category: "AI",
    icon: "scan-text",
    accent: "cyan",
    status: "ready",
    keywords: ["image to text", "ocr online", "screenshot to text"],
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    tagline: "Audio transcription",
    description:
      "Convert speech and audio files to text with timestamps. Growing demand for creators.",
    category: "AI",
    icon: "mic",
    accent: "emerald",
    status: "ready",
    keywords: ["speech to text", "audio transcription", "voice to text"],
  },
  {
    slug: "ai-paraphrase",
    name: "AI Paraphrasing Tool",
    tagline: "Rewrite text with AI",
    description:
      "Rephrase sentences and paragraphs while keeping meaning. Top SEO niche for content teams.",
    category: "AI",
    icon: "refresh-cw",
    accent: "violet",
    status: "ready",
    keywords: ["paraphrasing tool", "rewrite text ai", "rephrase"],
  },
  {
    slug: "ai-humanizer",
    name: "AI Humanizer",
    tagline: "Humanize AI text",
    description:
      "Make AI-generated copy sound natural and undetectable. The fastest-growing writing niche.",
    category: "AI",
    icon: "wand-2",
    accent: "fuchsia",
    status: "ready",
    featured: true,
    keywords: ["ai humanizer", "humanize ai text", "undetectable ai"],
  },
  {
    slug: "whois-lookup",
    name: "Domain WHOIS Lookup",
    tagline: "Registrar & expiry info",
    description: "Look up domain registration, expiry dates and nameserver records instantly.",
    category: "Network",
    icon: "search",
    accent: "amber",
    status: "ready",
    keywords: ["whois", "domain lookup", "registrar"],
  },
  {
    slug: "ip-lookup",
    name: "IP Address Lookup",
    tagline: "Geo & ISP details",
    description: "Resolve IP addresses to location, ISP, ASN and threat intelligence.",
    category: "Network",
    icon: "map-pin",
    accent: "cyan",
    status: "ready",
    keywords: ["ip lookup", "ip address", "geo ip"],
  },
  {
    slug: "speed-test",
    name: "Website Speed Test",
    tagline: "Core Web Vitals audit",
    description: "Measure load time, LCP, CLS and performance recommendations for any URL.",
    category: "Web",
    icon: "gauge",
    accent: "emerald",
    status: "ready",
    keywords: ["website speed test", "page speed", "performance"],
  },
  {
    slug: "meta-tags-generator",
    name: "Meta Tags Generator",
    tagline: "OG & Twitter cards",
    description: "Generate SEO meta tags, Open Graph and Twitter Card markup for any page.",
    category: "SEO",
    icon: "tags",
    accent: "violet",
    status: "ready",
    keywords: ["meta tags generator", "og tags", "seo meta"],
  },
  {
    slug: "robots-txt",
    name: "Robots.txt Generator",
    tagline: "Crawler rules builder",
    description: "Visual builder for robots.txt with allow/disallow rules and sitemap references.",
    category: "SEO",
    icon: "bot",
    accent: "fuchsia",
    status: "ready",
    keywords: ["robots.txt generator", "crawler", "disallow"],
  },
  {
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    tagline: "XML sitemap from URLs",
    description: "Paste URLs or crawl a site to generate a valid XML sitemap for search engines.",
    category: "SEO",
    icon: "map",
    accent: "amber",
    status: "ready",
    keywords: ["sitemap generator", "xml sitemap", "seo"],
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    tagline: "Validate & pretty-print",
    description: "Validate JSON syntax, pinpoint errors and format with syntax highlighting.",
    category: "Formatting",
    icon: "braces",
    accent: "violet",
    status: "ready",
    keywords: ["json validator", "json format", "pretty print"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    tagline: "Pretty-print & minify JSON",
    description:
      "Format, minify and validate JSON with syntax highlighting and error pinpointing.",
    category: "Formatting",
    icon: "braces",
    accent: "violet",
    status: "ready",
    keywords: ["json", "format", "pretty", "minify"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    tagline: "Shrink stylesheets",
    description: "Minify CSS for production with safe compression and size savings report.",
    category: "Formatting",
    icon: "minus",
    accent: "cyan",
    status: "ready",
    keywords: ["css minifier", "minify css", "compress css"],
  },
  {
    slug: "js-beautifier",
    name: "JavaScript Beautifier",
    tagline: "Format & prettify JS",
    description: "Beautify messy JavaScript with configurable indentation and line wrapping.",
    category: "Formatting",
    icon: "code-2",
    accent: "amber",
    status: "ready",
    keywords: ["javascript beautifier", "format js", "prettify"],
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    tagline: "Convert HTML to MD",
    description: "Transform HTML snippets into clean Markdown for docs and README files.",
    category: "Text",
    icon: "file-down",
    accent: "emerald",
    status: "ready",
    keywords: ["html to markdown", "convert html", "md"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    tagline: "Test patterns in real time",
    description:
      "Live-test regular expressions against sample text with match highlighting and groups.",
    category: "Formatting",
    icon: "regex",
    accent: "fuchsia",
    status: "ready",
    keywords: ["regex", "regexp", "pattern", "match"],
  },
  {
    slug: "csv-to-json",
    name: "CSV ⇄ JSON",
    tagline: "Convert between formats",
    description:
      "Convert CSV to JSON and back, with header detection and delimiter options.",
    category: "Formatting",
    icon: "file-spreadsheet",
    accent: "emerald",
    status: "ready",
    keywords: ["csv", "json", "convert", "parse"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder",
    tagline: "Encode & decode Base64",
    description: "Encode or decode Base64 strings and files, instantly in your browser.",
    category: "Encoding",
    icon: "binary",
    accent: "cyan",
    status: "ready",
    keywords: ["base64", "encode", "decode"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    tagline: "Inspect JSON Web Tokens",
    description:
      "Decode JWT header & payload, verify expiry, and inspect claims locally.",
    category: "Encoding",
    icon: "key-round",
    accent: "violet",
    status: "ready",
    keywords: ["jwt", "token", "decode", "auth"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    tagline: "Encode/decode URL strings",
    description:
      "Encode or decode URI components with one click. Handles edge cases reliably.",
    category: "Encoding",
    icon: "link-2",
    accent: "cyan",
    status: "ready",
    keywords: ["url", "uri", "encode", "decode"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    tagline: "Generate v1, v4, v7 UUIDs",
    description:
      "Generate single or bulk UUIDs in multiple versions with copy & export.",
    category: "Generators",
    icon: "hash",
    accent: "amber",
    status: "ready",
    keywords: ["uuid", "guid", "id", "generate"],
  },
  {
    slug: "api-tester",
    name: "API Tester",
    tagline: "Postman-style REST client",
    description:
      "Collections, environments, auth, params, JSON/form bodies, tests, and response inspector.",
    category: "Network",
    icon: "send",
    accent: "fuchsia",
    status: "ready",
    featured: true,
    keywords: ["api", "rest", "http", "request", "postman"],
  },
  {
    slug: "otp-detector",
    name: "OTP Detector",
    tagline: "Auto-extract verification codes",
    description:
      "Scan incoming messages and surface the 4–8 digit code instantly.",
    category: "Identity",
    icon: "shield-check",
    accent: "violet",
    status: "ready",
    keywords: ["otp", "code", "verify", "2fa"],
  },
  {
    slug: "code-reader",
    name: "Auto Code Reader",
    tagline: "Live OTP listener",
    description: "Stream verification codes as they arrive in your temp inbox.",
    category: "Identity",
    icon: "radio",
    accent: "amber",
    status: "ready",
    keywords: ["otp", "stream", "listener"],
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    tagline: "HEX, RGB, HSL, OKLCH",
    description: "Pick colors and convert across HEX, RGB, HSL and OKLCH formats.",
    category: "Color",
    icon: "pipette",
    accent: "fuchsia",
    status: "ready",
    keywords: ["color", "hex", "rgb", "hsl", "oklch", "picker"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    tagline: "WCAG accessibility ratios",
    description: "Check text/background contrast against WCAG AA & AAA thresholds.",
    category: "Color",
    icon: "shield-check",
    accent: "emerald",
    status: "ready",
    keywords: ["contrast", "wcag", "a11y", "accessibility"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum",
    tagline: "Placeholder text generator",
    description: "Generate paragraphs, sentences or words of placeholder copy.",
    category: "Text",
    icon: "type",
    accent: "amber",
    status: "ready",
    keywords: ["lorem", "ipsum", "placeholder", "text"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    tagline: "camel, snake, kebab, title",
    description: "Convert text between camelCase, snake_case, kebab-case, Title Case and more.",
    category: "Text",
    icon: "align-left",
    accent: "cyan",
    status: "ready",
    keywords: ["case", "camel", "snake", "kebab", "convert"],
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    tagline: "Compare two text blocks",
    description: "Side-by-side diff with inline highlighting for added & removed lines.",
    category: "Text",
    icon: "diff",
    accent: "violet",
    status: "ready",
    keywords: ["diff", "compare", "text", "merge"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    tagline: "Words, chars & reading time",
    description: "Count words, characters, sentences and estimated reading time.",
    category: "Text",
    icon: "calculator",
    accent: "emerald",
    status: "ready",
    keywords: ["word", "count", "characters", "reading"],
  },
  {
    slug: "html-stripper",
    name: "HTML Stripper",
    tagline: "Remove HTML tags",
    description: "Strip HTML markup from text while preserving readable content.",
    category: "Text",
    icon: "eraser",
    accent: "amber",
    status: "ready",
    keywords: ["html", "strip", "clean", "text"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    tagline: "Unix ⇄ ISO ⇄ Human",
    description: "Convert between Unix timestamps, ISO 8601 and human-readable dates.",
    category: "Time",
    icon: "clock",
    accent: "cyan",
    status: "ready",
    keywords: ["timestamp", "unix", "epoch", "date", "iso"],
  },
  {
    slug: "cron-parser",
    name: "Cron Parser",
    tagline: "Explain cron expressions",
    description: "Decode cron expressions into plain English with next-run previews.",
    category: "Time",
    icon: "clock",
    accent: "violet",
    status: "ready",
    keywords: ["cron", "schedule", "parser"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    tagline: "MD5, SHA-1, SHA-256, SHA-512",
    description: "Compute cryptographic hashes for any input string, locally.",
    category: "Security",
    icon: "fingerprint",
    accent: "fuchsia",
    status: "ready",
    keywords: ["hash", "md5", "sha", "checksum"],
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    tagline: "PNG, JPG, WebP, AVIF",
    description: "Convert images between PNG, JPG, WebP and AVIF in your browser.",
    category: "Media",
    icon: "image",
    accent: "violet",
    status: "ready",
    keywords: ["image", "convert", "png", "jpg", "webp"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    tagline: "px, rem, em, %, vh, vw",
    description: "Convert between CSS length units with a configurable root font size.",
    category: "Web",
    icon: "ruler",
    accent: "cyan",
    status: "ready",
    keywords: ["unit", "px", "rem", "em", "css"],
  },
  {
    slug: "user-agent-parser",
    name: "User-Agent Parser",
    tagline: "Decode UA strings",
    description: "Parse a User-Agent string into browser, OS and device details.",
    category: "Web",
    icon: "globe",
    accent: "emerald",
    status: "ready",
    keywords: ["user-agent", "ua", "browser", "parse"],
  },
  {
    slug: "html-entities",
    name: "HTML Entities",
    tagline: "Encode & decode entities",
    description: "Convert characters to and from HTML entity references.",
    category: "Encoding",
    icon: "code-2",
    accent: "fuchsia",
    status: "ready",
    keywords: ["html", "entities", "encode", "decode"],
  },
  {
    slug: "file-encode-decode",
    name: "File Encode/Decode",
    tagline: "Base64 files in the browser",
    description: "Encode or decode files to and from Base64 without uploading to a server.",
    category: "Encoding",
    icon: "binary",
    accent: "cyan",
    status: "ready",
    keywords: ["file", "base64", "encode", "decode"],
  },
  {
    slug: "string-utilities",
    name: "String Utilities",
    tagline: "Trim, reverse, sort & more",
    description: "Quick string transforms for everyday text cleanup and inspection.",
    category: "Text",
    icon: "type",
    accent: "violet",
    status: "ready",
    keywords: ["string", "trim", "reverse", "text"],
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    tagline: "Beautify HTML markup",
    description: "Format messy HTML into readable indented markup.",
    category: "Formatting",
    icon: "code-2",
    accent: "cyan",
    status: "ready",
    keywords: ["html", "format", "beautify"],
  },
  {
    slug: "json-to-xml",
    name: "JSON to XML",
    tagline: "Convert JSON to XML",
    description: "Turn JSON objects into XML documents instantly.",
    category: "Formatting",
    icon: "braces",
    accent: "emerald",
    status: "ready",
    keywords: ["json", "xml", "convert"],
  },
  {
    slug: "json-diff",
    name: "JSON Diff",
    tagline: "Compare two JSON documents",
    description: "Normalize and compare JSON side by side.",
    category: "Formatting",
    icon: "diff",
    accent: "fuchsia",
    status: "ready",
    keywords: ["json", "diff", "compare"],
  },
  {
    slug: "json-schema-generator",
    name: "JSON Schema Generator",
    tagline: "Schema from sample JSON",
    description: "Infer a JSON Schema from example JSON data.",
    category: "Formatting",
    icon: "braces",
    accent: "amber",
    status: "ready",
    keywords: ["json", "schema", "generator"],
  },
  {
    slug: "json-to-code",
    name: "JSON to Code",
    tagline: "Types from JSON",
    description: "Generate TypeScript or Python types from JSON samples.",
    category: "Formatting",
    icon: "code-2",
    accent: "violet",
    status: "ready",
    keywords: ["json", "typescript", "code"],
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    tagline: "Pretty-print XML",
    description: "Format and indent XML for readability.",
    category: "Formatting",
    icon: "file-code",
    accent: "cyan",
    status: "ready",
    keywords: ["xml", "format", "pretty"],
  },
  {
    slug: "xml-to-json",
    name: "XML to JSON",
    tagline: "Convert XML to JSON",
    description: "Parse XML and output JSON in the browser.",
    category: "Formatting",
    icon: "braces",
    accent: "emerald",
    status: "ready",
    keywords: ["xml", "json", "convert"],
  },
  {
    slug: "xml-to-csv",
    name: "XML to CSV",
    tagline: "XML rows to CSV",
    description: "Convert simple XML structures to CSV text.",
    category: "Formatting",
    icon: "file-spreadsheet",
    accent: "amber",
    status: "ready",
    keywords: ["xml", "csv", "convert"],
  },
  {
    slug: "csv-to-xml",
    name: "CSV to XML",
    tagline: "CSV rows to XML",
    description: "Turn CSV tables into XML documents.",
    category: "Formatting",
    icon: "file-spreadsheet",
    accent: "fuchsia",
    status: "ready",
    keywords: ["csv", "xml", "convert"],
  },
  {
    slug: "xml-validator",
    name: "XML Validator",
    tagline: "Check XML syntax",
    description: "Validate whether XML is well-formed.",
    category: "Formatting",
    icon: "shield-check",
    accent: "emerald",
    status: "ready",
    keywords: ["xml", "validate", "parser"],
  },
  {
    slug: "xml-to-code",
    name: "XML to Code",
    tagline: "Types from XML",
    description: "Convert XML to JSON then generate TypeScript types.",
    category: "Formatting",
    icon: "code-2",
    accent: "violet",
    status: "ready",
    keywords: ["xml", "typescript", "code"],
  },
  {
    slug: "encrypt-decrypt",
    name: "Encrypt / Decrypt",
    tagline: "AES-GCM with password",
    description: "Encrypt and decrypt text with a password using AES-GCM in your browser.",
    category: "Security",
    icon: "lock",
    accent: "amber",
    status: "ready",
    keywords: ["encrypt", "decrypt", "aes", "crypto"],
  },
];

const TRENDING_FIRST_SLUG = "api-tester";

export const featuredTools = (() => {
  const featured = tools.filter((t) => t.featured);
  const first = featured.find((t) => t.slug === TRENDING_FIRST_SLUG);
  if (!first) return featured;
  return [first, ...featured.filter((t) => t.slug !== TRENDING_FIRST_SLUG)];
})();

export const categoryCounts = categories.reduce(
  (acc, cat) => {
    acc[cat] = tools.filter((t) => t.category === cat).length;
    return acc;
  },
  {} as Record<ToolCategory, number>,
);

export const toolBySlug = (slug: string) => tools.find((t) => t.slug === slug);

export const accentClass: Record<Tool["accent"], string> = {
  violet: "from-[#7c3aed] to-[#6d28d9]",
  cyan: "from-[#2dd4bf] to-[#0d9488]",
  fuchsia: "from-[#ec4899] to-[#db2777]",
  amber: "from-[#fbbf24] to-[#f59e0b]",
  emerald: "from-[#34d399] to-[#10b981]",
};
