import {
  Braces,
  Regex,
  FileSpreadsheet,
  Binary,
  KeyRound,
  Link2,
  Hash,
  Send,
  Mail,
  Inbox,
  ShieldCheck,
  Radio,
  Palette,
  Type,
  Clock,
  Image as ImageIcon,
  QrCode,
  Lock,
  Diff,
  FileCode,
  Ruler,
  Globe,
  Code2,
  Eraser,
  Pipette,
  Calculator,
  Fingerprint,
  FileText,
  FileStack,
  Scissors,
  Minimize2,
  Bot,
  Database,
  Wand2,
  UserRound,
  Youtube,
  ScanText,
  Mic,
  RefreshCw,
  Search,
  MapPin,
  Gauge,
  Tags,
  Map,
  FileDown,
  Minus,
  AlignLeft,
  type LucideIcon,
} from "lucide-react";

export type ToolCategory =
  | "Encoding"
  | "Formatting"
  | "Generators"
  | "Network"
  | "Identity"
  | "Email"
  | "Text"
  | "Color"
  | "Time"
  | "Security"
  | "Web"
  | "Media"
  | "AI"
  | "PDF"
  | "SEO";

export interface Tool {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  category: ToolCategory;
  icon: LucideIcon;
  accent: "violet" | "cyan" | "fuchsia" | "amber" | "emerald";
  status: "ready" | "soon";
  keywords: string[];
  featured?: boolean;
}

export const categories: ToolCategory[] = [
  "Formatting",
  "Encoding",
  "Generators",
  "AI",
  "PDF",
  "Email",
  "Text",
  "Media",
  "Security",
  "Color",
  "Web",
  "SEO",
  "Network",
  "Identity",
  "Time",
];

export const tools: Tool[] = [
  {
    slug: "temp-mail",
    name: "Temp Mail",
    tagline: "Temporary email & fake inbox",
    description:
      "Disposable email for OTP, signups and testing. Millions use it daily for verifications without spam.",
    category: "Email",
    icon: Mail,
    accent: "emerald",
    status: "soon",
    featured: true,
    keywords: [
      "temp mail",
      "temporary email",
      "fake email generator",
      "disposable",
      "otp",
      "signup",
    ],
  },
  {
    slug: "temp-inbox",
    name: "Temp Inbox",
    tagline: "Live disposable inbox",
    description: "Real-time inbox viewer for your temp mail address with OTP auto-detection.",
    category: "Email",
    icon: Inbox,
    accent: "cyan",
    status: "soon",
    keywords: ["inbox", "email", "mail", "receive"],
  },
  {
    slug: "qr-generator",
    name: "QR Code Generator",
    tagline: "Custom colors, logo & analytics",
    description:
      "Create QR codes with custom colors, logo upload, dynamic URLs and scan analytics.",
    category: "Generators",
    icon: QrCode,
    accent: "amber",
    status: "soon",
    featured: true,
    keywords: ["qr code generator", "create qr code", "barcode", "dynamic qr"],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    tagline: "Reduce image size instantly",
    description:
      "Compress PNG, JPG and WebP in-browser. Perfect for bloggers, developers and students.",
    category: "Media",
    icon: Minimize2,
    accent: "violet",
    status: "soon",
    featured: true,
    keywords: ["compress image", "reduce image size", "optimize", "webp"],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    tagline: "Convert PDF to editable DOCX",
    description: "Transform PDF documents into editable Word files with layout preservation.",
    category: "PDF",
    icon: FileText,
    accent: "cyan",
    status: "soon",
    featured: true,
    keywords: ["pdf to word", "convert pdf", "docx"],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    tagline: "Combine multiple PDFs",
    description: "Drag, drop and merge PDF files into one document in seconds.",
    category: "PDF",
    icon: FileStack,
    accent: "fuchsia",
    status: "soon",
    keywords: ["merge pdf", "combine pdf", "join pdf"],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    tagline: "Extract pages from PDF",
    description: "Split PDFs by page range or extract individual pages as separate files.",
    category: "PDF",
    icon: Scissors,
    accent: "amber",
    status: "soon",
    keywords: ["split pdf", "extract pages", "pdf pages"],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    tagline: "Shrink PDF file size",
    description: "Reduce PDF size for email and uploads without losing readability.",
    category: "PDF",
    icon: Minimize2,
    accent: "emerald",
    status: "soon",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf"],
  },
  {
    slug: "ai-code-generator",
    name: "AI Code Generator",
    tagline: "Generate code with AI",
    description:
      "Describe what you need and get production-ready snippets in any language. Huge SaaS potential.",
    category: "AI",
    icon: Bot,
    accent: "violet",
    status: "soon",
    featured: true,
    keywords: ["ai code generator", "generate code with ai", "copilot"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    tagline: "Beautify & build queries",
    description:
      "Format and beautify SQL with syntax highlighting plus a visual query builder for developers.",
    category: "Formatting",
    icon: Database,
    accent: "cyan",
    status: "soon",
    featured: true,
    keywords: ["sql formatter", "sql beautifier", "query builder"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    tagline: "Strong passwords + breach check",
    description:
      "Generate secure passwords with strength scoring and Have I Been Pwned breach detection.",
    category: "Security",
    icon: Lock,
    accent: "emerald",
    status: "soon",
    featured: true,
    keywords: [
      "strong password generator",
      "secure password",
      "breach checker",
      "password strength",
    ],
  },
  {
    slug: "palette-generator",
    name: "Color Palette Generator",
    tagline: "Palettes & gradient builder",
    description:
      "Generate harmonious palettes, CSS gradients and export tokens for designers and developers.",
    category: "Color",
    icon: Palette,
    accent: "violet",
    status: "soon",
    featured: true,
    keywords: ["color palette generator", "gradient generator", "scheme", "design"],
  },
  {
    slug: "markdown-editor",
    name: "Markdown Editor",
    tagline: "Write & preview live",
    description:
      "Split-pane Markdown editor with live HTML preview. Built for GitHub developers and docs.",
    category: "Text",
    icon: FileCode,
    accent: "fuchsia",
    status: "soon",
    featured: true,
    keywords: ["markdown editor online", "markdown preview", "md editor"],
  },
  {
    slug: "ai-resume-builder",
    name: "AI Resume Builder",
    tagline: "AI CV generator",
    description:
      "Build ATS-friendly resumes and CVs with AI suggestions. High-traffic, professional templates.",
    category: "AI",
    icon: UserRound,
    accent: "amber",
    status: "soon",
    featured: true,
    keywords: ["resume builder", "ai cv generator", "curriculum vitae"],
  },
  {
    slug: "youtube-thumbnail",
    name: "YouTube Thumbnail Downloader",
    tagline: "HD thumbnails in one click",
    description: "Download max-resolution YouTube thumbnails by URL. Viral search volume tool.",
    category: "Media",
    icon: Youtube,
    accent: "fuchsia",
    status: "soon",
    keywords: ["youtube thumbnail downloader", "yt thumbnail", "video thumb"],
  },
  {
    slug: "image-to-text",
    name: "Screenshot to Text",
    tagline: "OCR online — image to text",
    description:
      "Extract text from screenshots and images with OCR. For students, offices and AI workflows.",
    category: "AI",
    icon: ScanText,
    accent: "cyan",
    status: "soon",
    keywords: ["image to text", "ocr online", "screenshot to text"],
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    tagline: "Audio transcription",
    description:
      "Convert speech and audio files to text with timestamps. Growing demand for creators.",
    category: "AI",
    icon: Mic,
    accent: "emerald",
    status: "soon",
    keywords: ["speech to text", "audio transcription", "voice to text"],
  },
  {
    slug: "ai-paraphrase",
    name: "AI Paraphrasing Tool",
    tagline: "Rewrite text with AI",
    description:
      "Rephrase sentences and paragraphs while keeping meaning. Top SEO niche for content teams.",
    category: "AI",
    icon: RefreshCw,
    accent: "violet",
    status: "soon",
    keywords: ["paraphrasing tool", "rewrite text ai", "rephrase"],
  },
  {
    slug: "ai-humanizer",
    name: "AI Humanizer",
    tagline: "Humanize AI text",
    description:
      "Make AI-generated copy sound natural and undetectable. The fastest-growing writing niche.",
    category: "AI",
    icon: Wand2,
    accent: "fuchsia",
    status: "soon",
    featured: true,
    keywords: ["ai humanizer", "humanize ai text", "undetectable ai"],
  },
  {
    slug: "whois-lookup",
    name: "Domain WHOIS Lookup",
    tagline: "Registrar & expiry info",
    description: "Look up domain registration, expiry dates and nameserver records instantly.",
    category: "Network",
    icon: Search,
    accent: "amber",
    status: "soon",
    keywords: ["whois", "domain lookup", "registrar"],
  },
  {
    slug: "ip-lookup",
    name: "IP Address Lookup",
    tagline: "Geo & ISP details",
    description: "Resolve IP addresses to location, ISP, ASN and threat intelligence.",
    category: "Network",
    icon: MapPin,
    accent: "cyan",
    status: "soon",
    keywords: ["ip lookup", "ip address", "geo ip"],
  },
  {
    slug: "speed-test",
    name: "Website Speed Test",
    tagline: "Core Web Vitals audit",
    description: "Measure load time, LCP, CLS and performance recommendations for any URL.",
    category: "Web",
    icon: Gauge,
    accent: "emerald",
    status: "soon",
    keywords: ["website speed test", "page speed", "performance"],
  },
  {
    slug: "meta-tags-generator",
    name: "Meta Tags Generator",
    tagline: "OG & Twitter cards",
    description: "Generate SEO meta tags, Open Graph and Twitter Card markup for any page.",
    category: "SEO",
    icon: Tags,
    accent: "violet",
    status: "soon",
    keywords: ["meta tags generator", "og tags", "seo meta"],
  },
  {
    slug: "robots-txt",
    name: "Robots.txt Generator",
    tagline: "Crawler rules builder",
    description: "Visual builder for robots.txt with allow/disallow rules and sitemap references.",
    category: "SEO",
    icon: Bot,
    accent: "fuchsia",
    status: "soon",
    keywords: ["robots.txt generator", "crawler", "disallow"],
  },
  {
    slug: "sitemap-generator",
    name: "Sitemap Generator",
    tagline: "XML sitemap from URLs",
    description: "Paste URLs or crawl a site to generate a valid XML sitemap for search engines.",
    category: "SEO",
    icon: Map,
    accent: "amber",
    status: "soon",
    keywords: ["sitemap generator", "xml sitemap", "seo"],
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    tagline: "Validate & pretty-print",
    description: "Validate JSON syntax, pinpoint errors and format with syntax highlighting.",
    category: "Formatting",
    icon: Braces,
    accent: "violet",
    status: "soon",
    keywords: ["json validator", "json format", "pretty print"],
  },
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    tagline: "Pretty-print & minify JSON",
    description:
      "Format, minify and validate JSON with syntax highlighting and error pinpointing.",
    category: "Formatting",
    icon: Braces,
    accent: "violet",
    status: "soon",
    keywords: ["json", "format", "pretty", "minify"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    tagline: "Shrink stylesheets",
    description: "Minify CSS for production with safe compression and size savings report.",
    category: "Formatting",
    icon: Minus,
    accent: "cyan",
    status: "soon",
    keywords: ["css minifier", "minify css", "compress css"],
  },
  {
    slug: "js-beautifier",
    name: "JavaScript Beautifier",
    tagline: "Format & prettify JS",
    description: "Beautify messy JavaScript with configurable indentation and line wrapping.",
    category: "Formatting",
    icon: Code2,
    accent: "amber",
    status: "soon",
    keywords: ["javascript beautifier", "format js", "prettify"],
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    tagline: "Convert HTML to MD",
    description: "Transform HTML snippets into clean Markdown for docs and README files.",
    category: "Text",
    icon: FileDown,
    accent: "emerald",
    status: "soon",
    keywords: ["html to markdown", "convert html", "md"],
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    tagline: "Test patterns in real time",
    description:
      "Live-test regular expressions against sample text with match highlighting and groups.",
    category: "Formatting",
    icon: Regex,
    accent: "fuchsia",
    status: "soon",
    keywords: ["regex", "regexp", "pattern", "match"],
  },
  {
    slug: "csv-to-json",
    name: "CSV ⇄ JSON",
    tagline: "Convert between formats",
    description:
      "Convert CSV to JSON and back, with header detection and delimiter options.",
    category: "Formatting",
    icon: FileSpreadsheet,
    accent: "emerald",
    status: "soon",
    keywords: ["csv", "json", "convert", "parse"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder",
    tagline: "Encode & decode Base64",
    description: "Encode or decode Base64 strings and files, instantly in your browser.",
    category: "Encoding",
    icon: Binary,
    accent: "cyan",
    status: "soon",
    keywords: ["base64", "encode", "decode"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    tagline: "Inspect JSON Web Tokens",
    description:
      "Decode JWT header & payload, verify expiry, and inspect claims locally.",
    category: "Encoding",
    icon: KeyRound,
    accent: "violet",
    status: "soon",
    keywords: ["jwt", "token", "decode", "auth"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    tagline: "Encode/decode URL strings",
    description:
      "Encode or decode URI components with one click. Handles edge cases reliably.",
    category: "Encoding",
    icon: Link2,
    accent: "cyan",
    status: "soon",
    keywords: ["url", "uri", "encode", "decode"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    tagline: "Generate v1, v4, v7 UUIDs",
    description:
      "Generate single or bulk UUIDs in multiple versions with copy & export.",
    category: "Generators",
    icon: Hash,
    accent: "amber",
    status: "soon",
    keywords: ["uuid", "guid", "id", "generate"],
  },
  {
    slug: "api-tester",
    name: "API Tester",
    tagline: "Lightweight REST client",
    description:
      "Send GET/POST/PUT/DELETE with headers, body & auth. Inspect responses inline.",
    category: "Network",
    icon: Send,
    accent: "fuchsia",
    status: "soon",
    keywords: ["api", "rest", "http", "request"],
  },
  {
    slug: "otp-detector",
    name: "OTP Detector",
    tagline: "Auto-extract verification codes",
    description:
      "Scan incoming messages and surface the 4–8 digit code instantly.",
    category: "Identity",
    icon: ShieldCheck,
    accent: "violet",
    status: "soon",
    keywords: ["otp", "code", "verify", "2fa"],
  },
  {
    slug: "code-reader",
    name: "Auto Code Reader",
    tagline: "Live OTP listener",
    description: "Stream verification codes as they arrive in your temp inbox.",
    category: "Identity",
    icon: Radio,
    accent: "amber",
    status: "soon",
    keywords: ["otp", "stream", "listener"],
  },
  {
    slug: "color-picker",
    name: "Color Picker",
    tagline: "HEX, RGB, HSL, OKLCH",
    description: "Pick colors and convert across HEX, RGB, HSL and OKLCH formats.",
    category: "Color",
    icon: Pipette,
    accent: "fuchsia",
    status: "soon",
    keywords: ["color", "hex", "rgb", "hsl", "oklch", "picker"],
  },
  {
    slug: "contrast-checker",
    name: "Contrast Checker",
    tagline: "WCAG accessibility ratios",
    description: "Check text/background contrast against WCAG AA & AAA thresholds.",
    category: "Color",
    icon: ShieldCheck,
    accent: "emerald",
    status: "soon",
    keywords: ["contrast", "wcag", "a11y", "accessibility"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum",
    tagline: "Placeholder text generator",
    description: "Generate paragraphs, sentences or words of placeholder copy.",
    category: "Text",
    icon: Type,
    accent: "amber",
    status: "soon",
    keywords: ["lorem", "ipsum", "placeholder", "text"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    tagline: "camel, snake, kebab, title",
    description: "Convert text between camelCase, snake_case, kebab-case, Title Case and more.",
    category: "Text",
    icon: AlignLeft,
    accent: "cyan",
    status: "soon",
    keywords: ["case", "camel", "snake", "kebab", "convert"],
  },
  {
    slug: "text-diff",
    name: "Text Diff",
    tagline: "Compare two text blocks",
    description: "Side-by-side diff with inline highlighting for added & removed lines.",
    category: "Text",
    icon: Diff,
    accent: "violet",
    status: "soon",
    keywords: ["diff", "compare", "text", "merge"],
  },
  {
    slug: "word-counter",
    name: "Word Counter",
    tagline: "Words, chars & reading time",
    description: "Count words, characters, sentences and estimated reading time.",
    category: "Text",
    icon: Calculator,
    accent: "emerald",
    status: "soon",
    keywords: ["word", "count", "characters", "reading"],
  },
  {
    slug: "html-stripper",
    name: "HTML Stripper",
    tagline: "Remove HTML tags",
    description: "Strip HTML markup from text while preserving readable content.",
    category: "Text",
    icon: Eraser,
    accent: "amber",
    status: "soon",
    keywords: ["html", "strip", "clean", "text"],
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    tagline: "Unix ⇄ ISO ⇄ Human",
    description: "Convert between Unix timestamps, ISO 8601 and human-readable dates.",
    category: "Time",
    icon: Clock,
    accent: "cyan",
    status: "soon",
    keywords: ["timestamp", "unix", "epoch", "date", "iso"],
  },
  {
    slug: "cron-parser",
    name: "Cron Parser",
    tagline: "Explain cron expressions",
    description: "Decode cron expressions into plain English with next-run previews.",
    category: "Time",
    icon: Clock,
    accent: "violet",
    status: "soon",
    keywords: ["cron", "schedule", "parser"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    tagline: "MD5, SHA-1, SHA-256, SHA-512",
    description: "Compute cryptographic hashes for any input string, locally.",
    category: "Security",
    icon: Fingerprint,
    accent: "fuchsia",
    status: "soon",
    keywords: ["hash", "md5", "sha", "checksum"],
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    tagline: "PNG, JPG, WebP, AVIF",
    description: "Convert images between PNG, JPG, WebP and AVIF in your browser.",
    category: "Media",
    icon: ImageIcon,
    accent: "violet",
    status: "soon",
    keywords: ["image", "convert", "png", "jpg", "webp"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    tagline: "px, rem, em, %, vh, vw",
    description: "Convert between CSS length units with a configurable root font size.",
    category: "Web",
    icon: Ruler,
    accent: "cyan",
    status: "soon",
    keywords: ["unit", "px", "rem", "em", "css"],
  },
  {
    slug: "user-agent-parser",
    name: "User-Agent Parser",
    tagline: "Decode UA strings",
    description: "Parse a User-Agent string into browser, OS and device details.",
    category: "Web",
    icon: Globe,
    accent: "emerald",
    status: "soon",
    keywords: ["user-agent", "ua", "browser", "parse"],
  },
  {
    slug: "html-entities",
    name: "HTML Entities",
    tagline: "Encode & decode entities",
    description: "Convert characters to and from HTML entity references.",
    category: "Encoding",
    icon: Code2,
    accent: "fuchsia",
    status: "soon",
    keywords: ["html", "entities", "encode", "decode"],
  },
];

export const featuredTools = tools.filter((t) => t.featured);

export const categoryCounts = categories.reduce(
  (acc, cat) => {
    acc[cat] = tools.filter((t) => t.category === cat).length;
    return acc;
  },
  {} as Record<ToolCategory, number>,
);

export const toolBySlug = (slug: string) => tools.find((t) => t.slug === slug);

export const accentClass: Record<Tool["accent"], string> = {
  violet: "from-[#7c3aed] to-[#6d28d9]",
  cyan: "from-[#2dd4bf] to-[#0d9488]",
  fuchsia: "from-[#ec4899] to-[#db2777]",
  amber: "from-[#fbbf24] to-[#f59e0b]",
  emerald: "from-[#34d399] to-[#10b981]",
};
